# -- Imports -----------------------------------------------------------------

from datetime import datetime

# -- Project information -----------------------------------------------------

project = "Cat's Knowledge Transfer"
copyright = f"{datetime.now().year}, Victoria Catlett"
author = "Victoria Catlett, victoria.w.catlett@gmail.com"

# The short X.Y version
version = "1.0.0"

# -- General configuration ---------------------------------------------------

extensions = [
    "myst_nb",
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.graphviz",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.viewcode",
    "sphinxcontrib.mermaid",
    "numpydoc",
    "sphinx_inline_tabs",
    "sphinx_copybutton",
    "sphinxemoji.sphinxemoji",
    "hoverxref.extension",
]

numpydoc_show_class_members = True
autosummary_generate = True

autodoc_docstring_signature = True
autodoc_default_options = {"members": None, "undoc-members": None}

# Make sure the targets are unique
autosectionlabel_prefix_document = True

# TODO: These appear to have no effect
mermaid_init_js = "mermaid.initialize({startOnLoad:true, useMaxWidth:false});"

# TODO: These appear to have no effect
mermaid_verbose = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["../_templates"]

# The suffix(es) of source filenames.
source_suffix = [".rst", ".md"]

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx
language = "en"

# Path patterns to exclude from doc generation
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = "sphinx_book_theme"

# Theme-specific options
html_theme_options = {
    "logo": {
        "image_light": "../_static/logo.png",
        "image_dark": "../_static/logo.png",
    },
    "show_toc_level": 2,
}

# Paths that contain custom static files
html_static_path = ["../_static"]

# The favicon
html_favicon = "../_static/favicon.png"


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder
htmlhelp_basename = "SDDdocs"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files
latex_documents = [
    (
        master_doc,
        "SDDdocs.tex",
        "SDD Documentation",
        ["GBO SDD"],
        "manual",
    )
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "SDDdocs", "SDD Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "SDDdocs",
        "SDD Documentation",
        author,
        "SDDdocs",
        "One line description of project.",
        "Miscellaneous",
    )
]

# The reST default role (used for this markup: `text`)
default_role = "obj"

# -- Extension configuration -------------------------------------------------
numpydoc_class_members_toctree = False

# -- Options for intersphinx extension ---------------------------------------

# Intersphinx mapping
intersphinx_mapping = {
    "astropy": ("https://docs.astropy.org/en/stable/", None),
    # "dysh": ("https://dysh.readthedocs.io/en/stable/", None),
    "matplotib": ("https://matplotlib.org/stable", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "python": ("https://docs.python.org/3/", None),
    "specutils": ("https://specutils.readthedocs.io/en/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    # "SDDdocs": ("http://docs.greenbankobservatory.org/software/", None),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# CSS files
html_css_files = [
    "css/custom.css",
]


# -- Settings for myst_nb notebook rendering ---------------------------------

# Cache notebooks to only re-run when cells change
nb_execution_mode = "cache"

# Where to store the notebook cache
nb_execution_cache_path = "jupyter_cache"


myst_enable_extensions = [
    "amsmath",
    "dollarmath",
]
myst_dmath_double_inline = True


# -- Settings for sphinx_copybutton ------------------------------------------

# Excluse prompt patterns from copying
copybutton_prompt_text = r">>> |\.\.\. |\$ |\(\w*\) \$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True


# -- Settings for sphinxemoji ------------------------------------------------

sphinxemoji_style = 'twemoji'


# -- Settings for hoverxref --------------------------------------------------

hoverxref_roles = [
    'numref',
    'confval',
    'setting',
    'term',
]